# /opt/docker-compose.yml
---
version: '2'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/media:/media
    ports:
      - 8080:8080
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    volumes:
      - /opt/appdata/transmission:/config
      - /mnt/media:/media
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/media:/media
    ports:
      - 8989:8989
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/couchpotato:/config
      - /mnt/media:/media
    ports:
      - 5050:5050
    links:
      - sabnzbd
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - sabnzbd
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media:/media
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    restart:
      always
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
      - transmission
    volumes:
      - /opt/appdata/jackett:/config
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Chicago
    restart:
      always
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
    volumes:
      - /opt/appdata/letsencrypt/config:/config
    environment:
      - PUID=1050
      - PGID=1050
      - TZ=America/Chicago
      - EMAIL=gregstengel@gmail.com
      - URL=gmachine.net
      - SUBDOMAINS=hollywood
      - ONLY_SUBDOMAINS=true
    restart:
      always
